FROM golang:1.19 as builder
WORKDIR /app
ADD . /app
RUN make build

FROM alpine:3.14
RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /
COPY --from=builder /app/config-prod.yaml /config.yaml
COPY --from=builder /app/ratings /
EXPOSE 8888
CMD [ "/ratings" ]