// Code generated by Kitex v0.6.1. DO NOT EDIT.

package ratingservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	rating "ratings/kitex_gen/rating"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetRating(ctx context.Context, Req *rating.QueryRatingReq, callOptions ...callopt.Option) (r *rating.QueryRatingResp, err error)
	CreateRating(ctx context.Context, Req *rating.CreateRatingReq, callOptions ...callopt.Option) (r *rating.CreateRatingResp, err error)
	UpdateRating(ctx context.Context, Req *rating.UpdateRatingReq, callOptions ...callopt.Option) (r *rating.UpdateRatingResp, err error)
	DeleteRating(ctx context.Context, Req *rating.DeleteRatingReq, callOptions ...callopt.Option) (r *rating.DeleteRatingResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRatingServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRatingServiceClient struct {
	*kClient
}

func (p *kRatingServiceClient) GetRating(ctx context.Context, Req *rating.QueryRatingReq, callOptions ...callopt.Option) (r *rating.QueryRatingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRating(ctx, Req)
}

func (p *kRatingServiceClient) CreateRating(ctx context.Context, Req *rating.CreateRatingReq, callOptions ...callopt.Option) (r *rating.CreateRatingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRating(ctx, Req)
}

func (p *kRatingServiceClient) UpdateRating(ctx context.Context, Req *rating.UpdateRatingReq, callOptions ...callopt.Option) (r *rating.UpdateRatingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRating(ctx, Req)
}

func (p *kRatingServiceClient) DeleteRating(ctx context.Context, Req *rating.DeleteRatingReq, callOptions ...callopt.Option) (r *rating.DeleteRatingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRating(ctx, Req)
}
