// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: idl/rating.proto

package rating

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_Success      Code = 0
	Code_ParamInvalid Code = 1
	Code_DBErr        Code = 2
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "Success",
		1: "ParamInvalid",
		2: "DBErr",
	}
	Code_value = map[string]int32{
		"Success":      0,
		"ParamInvalid": 1,
		"DBErr":        2,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_rating_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_idl_rating_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{0}
}

type Rating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ReviewID int64 `protobuf:"varint,2,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	Star     int64 `protobuf:"varint,3,opt,name=Star,proto3" json:"Star,omitempty"`
	GoodsID  int64 `protobuf:"varint,4,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
	Average  int64 `protobuf:"varint,5,opt,name=Average,proto3" json:"Average,omitempty"`
}

func (x *Rating) Reset() {
	*x = Rating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{0}
}

func (x *Rating) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rating) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *Rating) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Rating) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *Rating) GetAverage() int64 {
	if x != nil {
		return x.Average
	}
	return 0
}

type CreateRatingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewID int64 `protobuf:"varint,1,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	Star     int64 `protobuf:"varint,2,opt,name=Star,proto3" json:"Star,omitempty"`
	GoodsID  int64 `protobuf:"varint,3,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
}

func (x *CreateRatingReq) Reset() {
	*x = CreateRatingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingReq) ProtoMessage() {}

func (x *CreateRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingReq.ProtoReflect.Descriptor instead.
func (*CreateRatingReq) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRatingReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *CreateRatingReq) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *CreateRatingReq) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

type CreateRatingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=Code,proto3,enum=ratings.Code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateRatingResp) Reset() {
	*x = CreateRatingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingResp) ProtoMessage() {}

func (x *CreateRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingResp.ProtoReflect.Descriptor instead.
func (*CreateRatingResp) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRatingResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Success
}

func (x *CreateRatingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type QueryRatingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewID int64 `protobuf:"varint,1,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	GoodsID  int64 `protobuf:"varint,2,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
	Page     int64 `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64 `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *QueryRatingReq) Reset() {
	*x = QueryRatingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRatingReq) ProtoMessage() {}

func (x *QueryRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRatingReq.ProtoReflect.Descriptor instead.
func (*QueryRatingReq) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRatingReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *QueryRatingReq) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *QueryRatingReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryRatingReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating []*Rating `protobuf:"bytes,1,rep,name=Rating,proto3" json:"Rating,omitempty"`
	Total  int64     `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetRating() []*Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *Data) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QueryRatingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=Code,proto3,enum=ratings.Code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data *Data  `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *QueryRatingResp) Reset() {
	*x = QueryRatingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRatingResp) ProtoMessage() {}

func (x *QueryRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRatingResp.ProtoReflect.Descriptor instead.
func (*QueryRatingResp) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRatingResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Success
}

func (x *QueryRatingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryRatingResp) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRatingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeleteRatingReq) Reset() {
	*x = DeleteRatingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingReq) ProtoMessage() {}

func (x *DeleteRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingReq.ProtoReflect.Descriptor instead.
func (*DeleteRatingReq) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRatingReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRatingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=Code,proto3,enum=ratings.Code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *DeleteRatingResp) Reset() {
	*x = DeleteRatingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingResp) ProtoMessage() {}

func (x *DeleteRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingResp.ProtoReflect.Descriptor instead.
func (*DeleteRatingResp) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRatingResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Success
}

func (x *DeleteRatingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateRatingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ReviewID int64 `protobuf:"varint,2,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	Star     int64 `protobuf:"varint,3,opt,name=Star,proto3" json:"Star,omitempty"`
	GoodsID  int64 `protobuf:"varint,4,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
}

func (x *UpdateRatingReq) Reset() {
	*x = UpdateRatingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingReq) ProtoMessage() {}

func (x *UpdateRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingReq.ProtoReflect.Descriptor instead.
func (*UpdateRatingReq) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRatingReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRatingReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *UpdateRatingReq) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *UpdateRatingReq) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

type UpdateRatingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=Code,proto3,enum=ratings.Code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdateRatingResp) Reset() {
	*x = UpdateRatingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_rating_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingResp) ProtoMessage() {}

func (x *UpdateRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_rating_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingResp.ProtoReflect.Descriptor instead.
func (*UpdateRatingResp) Descriptor() ([]byte, []int) {
	return file_idl_rating_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRatingResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Success
}

func (x *UpdateRatingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_rating_proto protoreflect.FileDescriptor

var file_idl_rating_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x6c, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x7c, 0x0a, 0x06, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22,
	0x76, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x45, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x27, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x69,
	0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0d, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x6b, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x44, 0x22, 0x47, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x2a, 0x30, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x42, 0x45, 0x72, 0x72, 0x10, 0x02, 0x32, 0xa6, 0x02,
	0x0a, 0x0d, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_rating_proto_rawDescOnce sync.Once
	file_idl_rating_proto_rawDescData = file_idl_rating_proto_rawDesc
)

func file_idl_rating_proto_rawDescGZIP() []byte {
	file_idl_rating_proto_rawDescOnce.Do(func() {
		file_idl_rating_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_rating_proto_rawDescData)
	})
	return file_idl_rating_proto_rawDescData
}

var file_idl_rating_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_idl_rating_proto_goTypes = []interface{}{
	(Code)(0),                // 0: ratings.Code
	(*Rating)(nil),           // 1: ratings.Rating
	(*CreateRatingReq)(nil),  // 2: ratings.CreateRatingReq
	(*CreateRatingResp)(nil), // 3: ratings.CreateRatingResp
	(*QueryRatingReq)(nil),   // 4: ratings.QueryRatingReq
	(*Data)(nil),             // 5: ratings.Data
	(*QueryRatingResp)(nil),  // 6: ratings.QueryRatingResp
	(*DeleteRatingReq)(nil),  // 7: ratings.DeleteRatingReq
	(*DeleteRatingResp)(nil), // 8: ratings.DeleteRatingResp
	(*UpdateRatingReq)(nil),  // 9: ratings.UpdateRatingReq
	(*UpdateRatingResp)(nil), // 10: ratings.UpdateRatingResp
}
var file_idl_rating_proto_depIdxs = []int32{
	0,  // 0: ratings.CreateRatingResp.Code:type_name -> ratings.Code
	1,  // 1: ratings.Data.Rating:type_name -> ratings.Rating
	0,  // 2: ratings.QueryRatingResp.Code:type_name -> ratings.Code
	5,  // 3: ratings.QueryRatingResp.Data:type_name -> ratings.Data
	0,  // 4: ratings.DeleteRatingResp.Code:type_name -> ratings.Code
	0,  // 5: ratings.UpdateRatingResp.Code:type_name -> ratings.Code
	4,  // 6: ratings.RatingService.GetRating:input_type -> ratings.QueryRatingReq
	2,  // 7: ratings.RatingService.CreateRating:input_type -> ratings.CreateRatingReq
	9,  // 8: ratings.RatingService.UpdateRating:input_type -> ratings.UpdateRatingReq
	7,  // 9: ratings.RatingService.DeleteRating:input_type -> ratings.DeleteRatingReq
	6,  // 10: ratings.RatingService.GetRating:output_type -> ratings.QueryRatingResp
	3,  // 11: ratings.RatingService.CreateRating:output_type -> ratings.CreateRatingResp
	10, // 12: ratings.RatingService.UpdateRating:output_type -> ratings.UpdateRatingResp
	8,  // 13: ratings.RatingService.DeleteRating:output_type -> ratings.DeleteRatingResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_idl_rating_proto_init() }
func file_idl_rating_proto_init() {
	if File_idl_rating_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_rating_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRatingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRatingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRatingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRatingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRatingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_rating_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRatingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_rating_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_rating_proto_goTypes,
		DependencyIndexes: file_idl_rating_proto_depIdxs,
		EnumInfos:         file_idl_rating_proto_enumTypes,
		MessageInfos:      file_idl_rating_proto_msgTypes,
	}.Build()
	File_idl_rating_proto = out.File
	file_idl_rating_proto_rawDesc = nil
	file_idl_rating_proto_goTypes = nil
	file_idl_rating_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.6.1. DO NOT EDIT.

type RatingService interface {
	GetRating(ctx context.Context, req *QueryRatingReq) (res *QueryRatingResp, err error)
	CreateRating(ctx context.Context, req *CreateRatingReq) (res *CreateRatingResp, err error)
	UpdateRating(ctx context.Context, req *UpdateRatingReq) (res *UpdateRatingResp, err error)
	DeleteRating(ctx context.Context, req *DeleteRatingReq) (res *DeleteRatingResp, err error)
}
