// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReview = "reviews"

// Review mapped from table <reviews>
type Review struct {
	ID int64  `gorm:"column:id" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	GoodsID  int64  `gorm:"column:goods_id" json:"goods_id"`
	Content  string `gorm:"column:content" json:"content"`
	Author   string `gorm:"column:author" json:"author"`
}

// TableName Review's table name
func (*Review) TableName() string {
	return TableNameReview
}
