// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRating = "ratings"

// Rating mapped from table <ratings>
type Rating struct {
	ID       int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ReviewID int64 `gorm:"column:review_id" json:"review_id"`
	Star     int64 `gorm:"column:star" json:"star"`
	GoodsID  int64 `gorm:"column:goods_id" json:"goods_id"`
	Average  int64 `gorm:"column:average" json:"average"`
}

// TableName Rating's table name
func (*Rating) TableName() string {
	return TableNameRating
}
