// Code generated by hertz generator.

package review

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1_0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletereviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatereviewMw() []app.HandlerFunc {
	// your code...
	return nil
}
