// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	_ "reviews/biz/dal"
	_ "reviews/cmd/api/rpc/rating"
	"reviews/config"
	_ "reviews/config"
	_ "reviews/docs"
)

// @title  评价系统
// @version 1.0
// @description This is a demo using Hertz.

// @contact.name hertz-contrib
// @contact.url https://github.com/hertz-contrib

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @schemes http
func main() {
	h := server.Default(
		server.WithHostPorts(fmt.Sprintf(":%d", config.GetConfig().Server.Port)),
	)
	opts := accesslog.WithFormat("[${time}] ${status} - ${latency} ${method} ${url} ${reqBody} ${resBody}")

	h.Use(accesslog.New(opts))

	url := swagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))
	fmt.Println("Swagger: http://localhost:8080/swagger/index.html")
	register(h)
	h.Spin()
}
